//-----------------------------------------------------------------------------
// Packete.
package com.coopetico.coopeticobackend.entidades;
//-----------------------------------------------------------------------------
// Imports.
//-----------------------------------------------------------------------------

/**
 * Clase de temporal de datos del taxista.
 * Se envían los datos que han estado saltando de endpoint en endpoint
 * durante el proceso de solicitud de viaje y los datos del taxista asignado
 * en función unicamente del correo del taxista y no ningún otro dato.
 *
 * @author Joseph Rementeria (b5582 fd4)
 * @since 14-05-2019
 */
public class DatosTaxistaAsigadoEntidad {
    //-------------------------------------------------------------------------
    // Variables globales
    private String correoCliente;
    private String origen;
    private String destino;
    private String correoTaxista;
    private String nombreTaxista;
    private String fotoTaxista;
    private float estrellasTaxista;
    //-------------------------------------------------------------------------

    /**
     *
     * Constructor con todos los parmetros
     *
     * @param correoCliente correo del pasajero.
     * @param origen punto de origen.
     * @param destino punto de destino.
     * @param correoTaxista correo del taxista asignado.
     * @param nombreTaxista nombre y apellidos del taxista concatenados
     * @param fotoTaxista la foto del taxista
     * @param estrellasTaxista el promedio de estrellas de un taxista
     */
    public DatosTaxistaAsigadoEntidad(
        String correoCliente,
        String origen,
        String destino,
        String correoTaxista,
        String nombreTaxista,
        String fotoTaxista,
        float estrellasTaxista
    ) {
        this.correoCliente = correoCliente;
        this.origen = origen;
        this.destino = destino;
        this.correoTaxista = correoTaxista;
        this.nombreTaxista = nombreTaxista;
        this.fotoTaxista = fotoTaxista;
        this.estrellasTaxista = estrellasTaxista;
    }

    public DatosTaxistaAsigadoEntidad() {
    }
    //-------------------------------------------------------------------------
    // setters and getter autogenerated by MS VSC (Windows version).

    /**
     * @return the correoCliente
     */
    public String getCorreoCliente() {
        return correoCliente;
    }

    /**
     * @param correoCliente the correoCliente to set
     */
    public void setCorreoCliente(String correoCliente) {
        this.correoCliente = correoCliente;
    }

    public String getOrigen() {
        return origen;
    }

    public void setOrigen(String origen) {
        this.origen = origen;
    }

    public String getDestino() {
        return destino;
    }

    public void setDestino(String destino) {
        this.destino = destino;
    }

    public String getCorreoTaxista() {
        return correoTaxista;
    }

    public void setCorreoTaxista(String correoTaxista) {
        this.correoTaxista = correoTaxista;
    }

    public String getNombreTaxista() {
        return nombreTaxista;
    }

    public void setNombreTaxista(String nombreTaxista) {
        this.nombreTaxista = nombreTaxista;
    }

    public String getFotoTaxista() {
        return fotoTaxista;
    }

    public void setFotoTaxista(String fotoTaxista) {
        this.fotoTaxista = fotoTaxista;
    }

    public float getEstrellasTaxista() {
        return estrellasTaxista;
    }

    public void setEstrellasTaxista(float estrellasTaxista) {
        this.estrellasTaxista = estrellasTaxista;
    }
    //-------------------------------------------------------------------------
}
