//-----------------------------------------------------------------------------
// Packete.
package com.coopetico.coopeticobackend.entidades;
//-----------------------------------------------------------------------------
// Imports.
import java.sql.Timestamp;
//-----------------------------------------------------------------------------

/**
 * Clase de temporal a viajes. se
 *
 * @author Joseph Rementeria (b5582 fd4)
 * @since 14-05-2019
 */
public class ViajeComenzandoEntidad {
    //-------------------------------------------------------------------------
    // Variables globales
    private String correoCliente;
    private String origen;
    private String destino;
    //-------------------------------------------------------------------------

    /**
     *
     * Constructor con todos los parmetros
     *
     * @param correoCliente correo del pasajero.
     * @param origen punto de origen.
     * @param destino punto de destino.
     */
    public ViajeComenzandoEntidad(
        String correoCliente,
        String origen,
        String destino
    ) {
        this.correoCliente = correoCliente;
        this.origen = origen;
        this.destino = destino;
    }

    public ViajeComenzandoEntidad() {
    }
    //-------------------------------------------------------------------------
    // setters and getter autogenerated by MS VSC (Windows version).

    /**
     * @return the correoCliente
     */
    public String getCorreoCliente() {
        return correoCliente;
    }

    /**
     * @param correoCliente the correoCliente to set
     */
    public void setCorreoCliente(String correoCliente) {
        this.correoCliente = correoCliente;
    }

    public String getOrigen() {
        return origen;
    }

    public void setOrigen(String origen) {
        this.origen = origen;
    }

    public String getDestino() {
        return destino;
    }

    public void setDestino(String destino) {
        this.destino = destino;
    }
//-------------------------------------------------------------------------
}
