//-----------------------------------------------------------------------------
// Packete.
package com.coopetico.coopeticobackend.entidades;
//-----------------------------------------------------------------------------
// Imports.
import java.sql.Timestamp;
//-----------------------------------------------------------------------------
/**
 * Autor: Joseph Rementería (b55824).
 * Fecha: 18/04/2019.
 * 
 * Clase temporal previa a la insercin de una tupla de
 * viaje en la base de datos.
 */
public class ViajeTmpEntidad {
    //-------------------------------------------------------------------------
    // Variables globales
    private String placa;
    private String correoCliente;
    private String fechaInicio;
    private String fechaFin;
    private String costo;
    private Integer estrellas;
    private String origen;
    private String destino;
    private String correoTaxista;
    //-------------------------------------------------------------------------

    /**
     * 
     * Constructor con todos los parmetros
     * 
     * @param placa id del carro.
     * @param correoCliente correo del pasajero.
     * @param fechaInicio fecha de inicio del viaje.
     * @param fechaFin fecha de fin del viaje.
     * @param costo monto total del viaje.
     * @param estrellas calificación del pasajero al taxista
     * @param origen punto de origen.
     * @param destino punto de destino.
     * @param correoTaxista correo del conductor.
     */
    public ViajeTmpEntidad(
        String placa,
        String correoCliente,
        String fechaInicio,
        String fechaFin,
        String costo,
        Integer estrellas,
        String origen,
        String destino,
        String correoTaxista
    ) {
        this.placa = placa;
        this.correoCliente = correoCliente;
        this.fechaInicio = fechaInicio;
        this.fechaFin = fechaFin;
        this.costo = costo;
        this.estrellas = estrellas;
        this.origen = origen;
        this.destino = destino;
        this.correoTaxista = correoTaxista;
    }

    public ViajeTmpEntidad() {
    }
    //-------------------------------------------------------------------------
    // setters and getter autogenerated by MS VSC (Windows version).
    /**
     * @return the placa
     */
    public String getPlaca() {
        return placa;
    }

    /**
     * @param placa the placa to set
     */
    public void setPlaca(String placa) {
        this.placa = placa;
    }

    /**
     * @return the correoCliente
     */
    public String getCorreoCliente() {
        return correoCliente;
    }

    /**
     * @param correoCliente the correoCliente to set
     */
    public void setCorreoCliente(String correoCliente) {
        this.correoCliente = correoCliente;
    }

    /**
     * @return the fechaInicio
     */
    public String getFechaInicio() {
        return fechaInicio;
    }

    /**
     * @param fechaInicio the fechaInicio to set
     */
    public void setFechaInicio(String fechaInicio) {
        this.fechaInicio = fechaInicio;
    }

    /**
     * @return the fechaFin
     */
    public String getFechaFin() {
        return fechaFin;
    }

    /**
     * @param fechaFin the fechaFin to set
     */
    public void setFechaFin(String fechaFin) {
        this.fechaFin = fechaFin;
    }

    /**
     * @return the costo
     */
    public String getCosto() {
        return costo;
    }

    /**
     * @param costo the costo to set
     */
    public void setCosto(String costo) {
        this.costo = costo;
    }

    /**
     * @return the estrellas
     */
    public Integer getEstrellas() {
        return estrellas;
    }

    /**
     * @param estrellas the estrellas to set
     */
    public void setEstrellas(Integer estrellas) {
        this.estrellas = estrellas;
    }

    /**
     * @return the origen
     */
    public String getOrigen() {
        return origen;
    }

    /**
     * @param origen the origenDestino to set
     */
    public void setOrigen(String origen) {
        this.origen = origen;
    }

    /**
     * @return the destino
     */
    public String getDestino() {
        return destino;
    }

    /**
     * @param destino the destino to set
     */
    public void setDestino(String destino) {
        this.destino = destino;
    }

    /**
     * @return the correoTaxista
     */
    public String getCorreoTaxista() {
        return correoTaxista;
    }

    /**
     * @param correoTaxista the correoTaxista to set
     */
    public void setCorreoTaxista(String correoTaxista) {
        this.correoTaxista = correoTaxista;
    }
    //-------------------------------------------------------------------------
}
